- hosts: loadbalancer
  tasks:
  
  - name: "Install haproxy software"
    package:
        name: "haproxy"
        state: present

  - name: "copying the haproxy.cfg.j2 file to the loadBalancer"
    template:
        dest: "/etc/haproxy/haproxy.cfg"
        src: "haproxy.cfg"

  - name: "restarting the loadBalancer"
    service:
        name: "haproxy"
        state: restarted

- hosts: webserver
  tasks:

  - name: " Installing httpd"
    package:
        name: "httpd"
        state: present

  - name: " Installing php"
    package:
        name: "php"
        state: present

  - name: " Copying the file"
    copy:
        dest: "/var/www/html/"
        src:  "/var/www/html/index.php"
  
  - name: " Starting the httpd"
    service:
        name: "httpd"
        state: started



